# --- CONFIGURACIÓN MYSQL (NUEVA) ---

# Conexión a tu base de datos 'lp3_db' en el puerto 3306
spring.datasource.url=jdbc:mysql://localhost:3306/lp3_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Tus credenciales (las que creamos en la terminal)
spring.datasource.username=alumno
spring.datasource.password=secreto

# El Driver oficial de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- HIBERNATE (Para que cree las tablas sola) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect